name: Upload File to OCI Bucket

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [master]  # Change this to your preferred branch (e.g., 'main' or 'master')

env:
  OCI_REGION: 'me-riyadh-1'  # Change to your OCI region
  OCI_NAMESPACE: 'axjejvuhn1me'  # Your OCI namespace
  OCI_BUCKET: 'githubaction-demo-1'  # Your OCI bucket name

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Python and pip
      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      # Step 3: Install OCI CLI
      - name: Install OCI CLI
        run: |
          python3 -m pip install oci-cli --upgrade
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          oci --version

      # Step 4: Configure OCI CLI using credentials from GitHub secrets
      - name: Configure OCI CLI
        env:
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_KEY_PASSPHRASE: ${{ secrets.OCI_KEY_PASSPHRASE }}
        run: |
          mkdir -p ~/.oci
          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=${OCI_USER_OCID}
          fingerprint=${OCI_FINGERPRINT}
          tenancy=${OCI_TENANCY_OCID}
          region=${{ env.OCI_REGION }}
          key_file=~/.oci/oci_api_key.pem
          pass_phrase=${OCI_KEY_PASSPHRASE}
          EOF
          
          cat > ~/.oci/oci_api_key.pem <<EOF
          $OCI_PRIVATE_KEY
          EOF
          
          chmod 600 ~/.oci/oci_api_key.pem ~/.oci/config

      # Step 5: Verify OCI Authentication
      - name: Verify OCI Authentication
        run: |
          oci os ns get

      # Step 6: Upload a specific file to OCI bucket
      - name: Upload File to OCI Bucket
        env:
          OCI_BUCKET: ${{ env.OCI_BUCKET }}
          OCI_NAMESPACE: ${{ env.OCI_NAMESPACE }}
        run: |
          # Specify the file you want to upload here
          FILE_PATH="path/to/your/file.txt"  # Replace with the path to the file you want to upload
          
          # Upload the file to the OCI bucket
          oci os object put \
            --namespace $OCI_NAMESPACE \
            --bucket-name $OCI_BUCKET \
            --file $FILE_PATH \
            --name $(basename $FILE_PATH) \
            --force
          
          echo "File uploaded successfully to OCI bucket"
